import React, { useEffect, useState } from "react";
import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import { Footer } from "../components/Footer";
const inter = Inter({ subsets: ["latin"] });
import { Technologic } from "../components/Technologic";
import { Details } from "../components/Details";
import axios from "axios";
const URL = "http://localhost:5000/api/getPdf/63b408f1562a8c1fde6598bc";

export default function Home() {
  const [apiData, setApiData] = useState(null);

  useEffect(() => {
    axios(URL)
      .then((res) => setApiData(res.data.data))
      .catch((err) => console.error(err));
  }, []);

if(!apiData){
  return "Loading..."
}
  return (
    <>
      <Head>
        <title>CV App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.main}>
        <div className="flex app">
          <Details {...apiData} />
          <Technologic {...apiData} />
        </div>
        <Footer />
      </div>
    </>
  );
}
